import { format, addDays } from "npm:date-fns@3.6.0";
export function validateAndPrepareData(requestData) {
  console.log("Validating request data:", {
    hasJob: !!requestData.job,
    hasArtist: !!requestData.artist,
    hasBankDetails: !!requestData.bankDetails,
    hasInvoiceSettings: !!requestData.invoiceSettings
  });
  if (!requestData.job) {
    throw new Error("Job data is missing");
  }
  if (!requestData.artist) {
    throw new Error("Artist data is missing");
  }
  if (!requestData.bankDetails) {
    throw new Error("Bank details are missing");
  }
  if (!requestData.invoiceSettings) {
    throw new Error("Invoice settings are missing");
  }
  const { job, artist, invoiceSettings, amount, gstAmount, bankDetails } = requestData;
  console.log("Padd, " + gstAmount);
  console.log("Data validation successful:", {
    invoiceNumber: "Will be generated by database",
    amount,
    gstAmount,
    jobTitle: job.title,
    artistName: artist.name
  });
  return {
    job,
    artist,
    invoiceSettings,
    amount,
    gstAmount,
    bankDetails
  };
}
export function formatInvoiceDates(invoiceSettings) {
  const invoiceDate = new Date();
  const dueDate = addDays(invoiceDate, invoiceSettings.paymentTerms || 14);
  return {
    formattedInvoiceDate: format(invoiceDate, "dd MMM yyyy"),
    formattedDueDate: format(dueDate, "dd MMM yyyy")
  };
}
export async function sendInvoiceEmail(resend, job, artist, invoiceNumber, total, invoiceSettings, pdfBase64, shouldCopyArtist) {
  const emailSubject = `Invoice ${invoiceNumber} from ${artist.name}`;
  // Format the current date in DD Mon YYYY format
  const currentDate = format(new Date(), "dd MMM yyyy");
  const emailBody = `
  <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MUSEIO Email Templates</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #ffffff;
    }
    .logo-container {
      text-align: center;
      padding: 20px 0;
      background-color: #ffffff;
    }
    .logo-container img {
      max-width: 200px;
      height: auto;
      width: auto;
      max-height: 80px;
    }
    .email-section {
      margin: 0 auto 40px;
      max-width: 620px;
      background-color: #ffffff;
      border-radius: 12px;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.06);
      overflow: hidden;
    }
    .email-header {
      background: linear-gradient(90deg, #E9D5FF 0%, #DDD6FE 100%);
      padding: 24px 24px 12px;
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
    }
    .email-brand {
      font-weight: bold;
      font-size: 24px;
      color: #ffffff;
    }
    .email-logo {
      max-width: 120px;
      max-height: 60px;
      width: auto;
      height: auto;
    }
    .email-meta {
      text-align: right;
      font-size: 14px;
      color: #374151;
    }
    .email-body {
      background-color: #ffffff;
      padding: 24px;
    }
    .email-body h3 {
      font-size: 20px;
      margin-bottom: 12px;
      color: #111827;
      background-color: #ffffff;

    }
    .email-body p {
      font-size: 15px;
      color: #4B5563;
      margin-bottom: 20px;
      background-color: #ffffff;

    }
    .email-body ul {
      list-style: none;
      padding: 0;
      font-size: 15px;
      color: #111827;
      line-height: 1.8;
      background-color: #ffffff;

    }
    .email-body ul li strong {
      color: #111827;
    }
    .email-footer {
      padding: 24px;
      font-size: 13px;
      color: #6B7280;
      text-align: center;
      background-color: #f9fafb;
      border-top: 1px solid #e5e7eb;
    }
    @media only screen and (max-width: 600px) {
      .logo-container img {
        max-width: 150px;
        max-height: 60px;
      }
      .email-header {
        flex-direction: column;
        align-items: flex-start;
      }
      .email-meta {
        text-align: left;
        margin-top: 10px;
      }
      .email-logo {
        max-width: 100px;
        max-height: 50px;
        margin-top: 10px;
      }
    }
  </style>
</head>
<body>

  <div class="logo-container">
    <img 
      src="https://museioapp.com/museio-gradient-logo.svg" 
      alt="Museio Logo"
    />
  </div>
<section class="email-section">
    <div class="email-header" style="background: linear-gradient(90deg, #E9D5FF 0%, #DDD6FE 100%);">
      <div class="email-meta" style="text-align: left;">
        <div style="font-size: 22px; font-weight: bold; margin-bottom: 8px;">Invoice Sent</div>
        <div style="font-size: 14px; color: #4B5563;">${currentDate}</div>
        <div style="font-size: 14px; color: #4B5563; font-weight: bold;">Total: A$${total}</div>
      </div>
    </div>
    <div class="email-body">
      <h3>💼 You have received a new invoice</h3>
      <p>Here's a summary of the completed job and the billing information:</p>
      <ul>
        <li><strong>Event:</strong> ${job.title}</li>
        <li><strong>Date:</strong> ${format(new Date(job.date), "dd MMM yyyy")} </li>
        <li><strong>Time:</strong> ${job.start_time} – ${job.end_time}</li>
        <li><strong>Location:</strong> ${job.location} </li>
        <li><strong>Invoice #:</strong> ${invoiceNumber}</li>
        <li><strong>Name:</strong> ${artist.name} </li>
        <li><strong>Email:</strong> <a href="${artist.email}">${artist.email}</a></li>
        ${artist.phone ? `<li><strong>Phone:</strong> ${artist.phone}</li>` : ''}
      </ul>
      <p>📎 Your invoice is attached in PDF format.</p>
      <p style="font-style: italic; color: #6B7280;">If you have any questions, please reach out to ${artist.name}.</p>
      <p>Warm regards,<br>
      <strong>Museio Team</strong><br>
      <a href="mailto:support@museioapp.com">support@museioapp.com</a></p>
    </div>
    <div class="email-footer">
      <a href="https://museioapp.com/" style="
        display: inline-block;
        margin-top: 0;
        padding: 10px 18px;
        background: linear-gradient(90deg, #D8B4FE 0%, #C084FC 100%);
        color: #ffffff;
        text-decoration: none;
        border-radius: 6px;
        font-weight: 500;
        font-size: 14px;
        margin-bottom: 12px;">
        Discover Museio
      </a>
      <p style="margin-top: 8px; font-size: 13px; color: #6B7280;">
        <span style="font-size: 13px; font-weight: 500;">Transform your <strong>Passion</strong> into a <strong>Business</strong></span>
      </p>
      <p style="margin-top: 16px; font-size: 13px; color: #6B7280;">
        <span style="font-size: 12px;">This email was automatically generated by <strong>MuseioApp</strong>.</span>
      </p>
    </div>
  </section>
  </body>
</html>
  `;
  const emailData = {
    from: `Museio Invoice <invoice@museioapp.com>`,
    to: [
      job.contact_email
    ],
    subject: emailSubject,
    html: emailBody,
    attachments: [
      {
        filename: `invoice-${invoiceNumber}.pdf`,
        content: pdfBase64
      }
    ]
  };
  // Add CC if artist wants email copies
  if (shouldCopyArtist) {
    console.log("Including artist in CC:", artist.email);
    emailData.cc = [
      artist.email
    ];
  }
  const { error } = await resend.emails.send(emailData);
  if (error) {
    throw new Error(`Resend API error: ${error.message}`);
  }
}
